# Generated by Django 4.2.5 on 2023-12-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.category",
            ),
            preserve_default=False,
        ),
    ]
